# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf40e6a3421f226cd384978a89632ee2b17a0a7b6097116472af63cd0cccc9a8d432d9bf7ae32cab0f575ad4cbe4a60b9a5a44b28f87c43d721d3c395196c76
  recaptcha_secret_key: <%= ENV['RECAPCHA_PRIVATE_KEY'] %>
  
test:
  secret_key_base: 83cbba11e297bd43aac1d026608e474b6cf0e470ef115b466d1a55360ae2aca111f924bd33930455fdcef4d79084523da58e2a23521b619595db02d54bcad6fa
  recaptcha_secret_key: <%= ENV['RECAPCHA_PRIVATE_KEY'] %>
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_secret_key: <%= ENV['RECAPCHA_PRIVATE_KEY'] %>